---
title: "p8105_hw2_ss7332"
author: "Sean Sorek"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      comment = NA)
library(tidyverse)
library(readxl)
```

# Problem 1

```{r}
transit <- read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |> 
  select(Line, starts_with("Station"), starts_with("Route"),
         Vending, `Entrance Type`, ADA, Entry) |>
  mutate(Entry = Entry |> case_match("YES" ~ T, "NO" ~ F))

glimpse(transit)
```

# Problem 2

```{r}
mr_trash_wheel <- read_excel(
  "data/202409 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel", skip = 1, col_names = TRUE
) |> select(-starts_with("...")) |> filter(!is.na(Dumpster)) |> mutate(`Sports Balls` = as.integer(floor(`Sports Balls`)), Wheel = "Mr. Trash Wheel")

pf_trash_wheel <- read_excel(
  "data/202409 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel", skip = 1, col_names = TRUE
) |> select(-starts_with("...")) |> filter(!is.na(Dumpster)) |> mutate(Wheel = "Professor Trash Wheel")

gw_trash_wheel <- read_excel(
  "data/202409 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda Trash Wheel", skip = 1, col_names = TRUE
) |> select(-starts_with("...")) |> filter(!is.na(Dumpster)) |> mutate(Wheel = "Gwynnda Trash Wheel")
```

